# Based on https://simonwillison.net/2020/Oct/9/git-scraping/
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://currents.soest.hawaii.edu/uhdas_fromships/armstrong/daily_report/shorestatus.txt > armstrong.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
